### ISSUE TITLE
Improvement of drawing permissions for shared protected board

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#111]
Dear François,

First of all I hope you are fine, and I wish you a happ**ier** new year ;-)

But new year, new problems!
I have shared a board with a colleague (say A) without privilege (for him) to write on the board.
1. I set a shared board with password and configure it so that nobody can write
2. I give the link to A, and he opens this board (as expected, he cannot draw)
3. I close my window and open a new window (on the previous link)
From now on I seem to be another participant because I am now required to give my password in order to get all privileges (as I see it in the menu), BUT:
4. A still cannot see his drawings while I can see them on my screen!
5. I still can draw on the screen (without privileges, remember) and A can see my new drawings on his screen
6. if A presses F5, he will see all the drawings (his preceding ones, that he couldn't see until now, and all mines) and A can draw now

I think nobody (even me from point 3)  should be able to draw without giving the password.
What do you think?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
I am fine but quite busy, I guess like many of us :). Happier new year to you too!
Thank you for having found that bug. I perfectly agree with you. I am so sorry, the thing is that I never use that functionnality! So I just forgot about problems with privileges. The issue is now only partially solved... partially because other users may still undo, redo, draw a vertical line to divide the screen, create magnets etc. :)
Work in progress...

**Comment by philardine** [comment]
Dear François,
Happy to hear you are fine!
Thank you for all the good work, for your creative imagination and generosity, and for your (as always) nice and quick answer :-)

**Comment by francoisschwarzentruber** [comment]
Thank you for your kind message. Did you experience these kind of troubles again?

**Comment by philardine** [comment]
So far, no.

**Comment by francoisschwarzentruber** [comment]
OK. Now, we should have even less problems. :) I think it really works. Well, I must confess that the architecture is not fully secure. One could easily hack the system and write even he/she is not allowed. But as courses, presentations, are not *very* sensitive, I think we can continue like this. :)

**Comment by philardine** [comment]
Hello François,

I am sorry but there is still something weird with protected boards and privileges.
To reproduce the bug hereafter, there must be no other frame sharing the protected board before point 2.
1. make a protected board with password and don't allow write permission
2. quit the frame
3. anybody opening a new frame on this board has no privileges and can draw on the board

I would expect nobody can draw until he types the correct password...

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

thank you for your comment. That behavior is "normal". In Tableaunoir, boards are ephemeral: a board only exists if there are some users, and if you quit the frame, then, as you are the single user, the board is lost. There are several reasons:
- the deployment of Tableaunoir is light because it does not remember anything
- also Tableaunoir preserves your privacy because it stores nothing
- it is more difficult to "attack" the server since it has never to store a huge amount of information
This could be changed of course. But some persons like the fact that boards are ephemeral. As I guess, you would prefer to prepare an URL in advance, protect it, etc. right?

**Comment by tekhnee** [comment]
If I may chime in, it would be nice to be able to prepare a board for a lecture, laying out one's PDFs and a few preliminary zdrawings, and organizing a rough narrative for the session—all on the night before, without worrying about data persistence. Tableaunoir makes this possible already, to some extent, via the Export functionality. Two alternative approaches towards greater persistence could be:

1. All tableau layers embedded within the saved `.tableaunoir` file, including background images and PDFs.

This would potentially result in enormous files, though, and could be prone to data corruption.

2. A UI and backend infrastructure for storing tableaux and their embeds (PDFs, images) on the server.

This would involve a lot of graceless work on François's part. More interesting, however, would be a secure REST API via which tableaunoir could be interfaced with the file systems of existing cloud services (Moodle, NextCloud, etc.). Effectively, this would enable authors and sysadmins to turn tableaunoir from a standalone app into a plugin with minimal effort.

Meanwhile, I think François has struck a good balance of simplicity and power with his export function.

**Comment by francoisschwarzentruber** [comment]
Dear tekhnee,

thank you for your comment. Your point 1 is easy to implement. Of course... .tableaunoir should embed the background too. Sorry for that, I will do it, probably tomorrow (today = busy all the day). 
REST API could be interesting... I do not know at all how it works!

Have a good day.

**Comment by philardine** [comment]
Hello Tekhnee and François,

Thank you for the explanation, I understand the ephemeral principle of tableaunoir and agree.

Nevertheles, I think I was not clear enough. So please let me argue a little more:
1. make a protected board with password and don't allow write permission
2. quit the frame
3. anybody opening a new frame on this board "do not have any privileges" according to menu/share configuration but everybody can draw on the board -> **I think it's inconsistent**
4. moreover, when one gives the password (thus becoming a privileged one) no other user should be able to write (see menu/share configuration: "All users can write" is not checked - and btw the little image following the checkbox has disappeared) but everybody can still draw -> **I think it's inconsistent too**
5. finally, when the privileged one checks "All users can write" then immediately unchecks, other users finally cannot write!

Or did I miss something?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
Thank you for your reformulation. That is very clear now. I completely understand you, and you are right. This is inconsistent. It will be solved soon, + storing the documents behind in .tableaunoir files! :)
Have a nice evening.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

there are two ways to solve the inconsistency (in the current state, the protection is persistent but not the privileges, which is a non sense). Which one do you prefer?

Option 1. Protection and privileges are persistent.
At your step 3, the user should not be able to write.

Option 2. Protection and privileges are ephemeral.
At your step 3, as the board has been deleted, a new board is created with the same URL. By default, there is no protection and everybody can write.

Maybe option 1 makes more sense, no?

**Comment by philardine** [comment]
Dear François,

Thank you for your perseverance :-)
The option 1 is precisely what I expected.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
the easiest for me is the following. The server only stores the password, but not the privilege option. But on a protected board, the default is: nobody can draw. So we would have the following scenario.

1. make a protected board with password and don't allow write permission (or allow write permission)
2. quit the frame
3. sombody opening a new frame on this board "will not have any privileges" (that is the default value for protected board) ** and cannot draw on the board**

**Comment by philardine** [comment]
Dear François,

I like this proposal.
The only way to acquire write permission is to give the password, which corresponds to the (implicit?) specification of this feature as far as I guess it.

When you open a protected board without write permission in point 1, then in point 3 you cannot write on the board whether you are the creator or not, because you opened a new frame and the owner has logged out (so you are considered a new user, even if you were that guy).

And, to be sure, do you agree with the following: if in point 1 you give write access to any user, then in point 3 any user connecting to the board will have the opportunity to give the password but can still write to the board?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

I agree with your points. The next implementation will have the following behaviour. Is that scenario ok?

1. make a protected board with password and allow write permission for everybody (x).
2. quit the frame
3. you and some other users open a new frame on this board and "will not have any privileges" (that is the default value for protected board) and cannot draw on the board.
4. you write the correct password. You become root. You can write. **Others cannot write** (because the value (x) hasnot been stored)
5. You can give permissions to write to everybody by clicking on the checkbox

Have a nice day!

PS: In case of several root users, the checkbox will however be inconsistent. ;). As this case is rare, I think we do not care no? Anyway, in that case, any root could disallow other users to write including other roots. But other roots may again toggle the checkbox etc. For the moment the checkout status will be a bit inconsistent in that case.

**Comment by francoisschwarzentruber** [comment]
The issue is I think fixed. But it needs to be checked.
PS: Also, now, the toolbar is "blinking" when you reach a shared board. Why? Because by default you cannot write! Then the server tells you about your privilege.

**Comment by philardine** [comment]
Dear François,

Please excuse my silence until now...

Maybe I got confused throughout this long exchange, but the fact is that I am not comfortable with your last scenario.

I wonder whether the architecture of this app comply to MVC (Model-View-Controller) or not: perhaps the board data only exist on the client side and every drawing is forwarded to all participants? If this is the case, I don't understand how a board can survive to its owner disconnection.

On the other side, if the board content is stored on a server, I think the program should conform to MVC or one of its variants...
In my vision of things (according to MVC):
1. A board is protected iff it is created with a password. This is a property of the board and is persisted with it.
2. A protected board can allow users to write. This rights is a property of the board (not of the users) and it is persisted with the board.
1. If the protected board allows writing, every user can write.
1. If the protected board doesn't allow writing, you must be a privileged user to be able to write. Ordinary users cannot.
1. Only privileged users can modify the writing rights state of the board.
1. Each user who gives the password becomes a privileged user (the creator is thus a privileged user, as any other privileged user).
1. Privilege state is a property of the user and it is ephemeral: if you come back later, you have to give the password again to grant privilege.
1. Privileged user can see a checkbox showing the write rights (no inconsistency possible here as we see the only one state variable belonging to the board).
1. Privileged user can set the write rights via this checkbox.
1. When a privileged user set (or unset) write rights, every other privileged user is notified.

I didn't dive into the code of tableaunoir and maybe I am off the mark...?

PS : Btw I suffered a recurring message "Impossible to connect to the server" this afternoon (2021/02/12 at 16:22)

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

thank you for your message. I will understand to your points.

>>> I wonder whether the architecture of this app comply to MVC (Model-View-Controller) or not: perhaps the board data only exist on the client side and every drawing is forwarded to all participants? 
- The board only exists on the client side for privacy reasons. Every drawing is forwarded to all other participants. In this sense, Tableaunoir is decentralized.
- The server only stores the id of the board, the password, if there is one, plus ids of the users and their associated websockets.

>>> If this is the case, I don't understand how a board can survive to its owner disconnection.
- As long the board exists somewhere, one of the existing user is designated to send the board data to the new user.

1. I agree, and it is actually like that.
2. Currently the permissions are properties of users. We could imagine some future improvement of Tableaunoir where the root user could give the write permissions to users A and B but not to users C and D, whereas A and B are not root. (*)
3. Yes, for the moment, it is like this. The weird example (*) of writing permissions above is not possible.
4. Currently it is like this. But technically, we could decide to allow for generalization and allow situations like (*).
5. Yes.
6. Yes.
7. Yes. The server does not store any personal information, so it can tell if a user was a previous user or not.
8. Yes, but I really do not like this checkbox as it is now, the implementation is incorrect when there are several root users (see next message)
9. Yes.
10. Oh, interesting idea to be noticed!

PS: Really sorry the server crashed :(. I just rebooted the server. I think there is a bug in the server part, the server should not have crashed I think. The issue is that the server is written in JS which not strongly typed while the client side is in Typescript which is strongly typed. I have difficulties to put the server because Typescript is difficult to configure.

**Comment by francoisschwarzentruber** [comment]
Currently, this checkbox is badly implemented:
a) when checked, all users can write (that is ok)
b) when unchecked, nobody can write except the root user who clicked on it (especially other root users cannot write, which is stupid).

Before making some modifications, I would like to have your point on view on user privileges.

1. Do we have situations where there are several root users? If no, the inconsistency b) is not dramatic, and it is not urgent to repair it.
2. Do we have situations where we give writing permission to a non-root user? (I guess so? We could ask a question to a specific student and she could write down the answer and only she?) The interface will be too complicated maybe?
3. Or should we just fix to your current idea: just toggle between "all users can write" and "only root users can write"?

Thank you for your support.

**Comment by philardine** [comment]
Dear François,

I need some precision about the way board data are stored.
1. A creates a protected board and writes "Hello!"
2. A quit the frame (nobody owns the board from now on)
3. A comes back to the board within a new frame

Is it true that A doesn't see "Hello!" at point 3, but rather a fresh board?

1. A creates a protected board and writes "Hello!" and sends the link to B and C
2. B and C connect to the board which is stored on A client machine.
3. A quit the frame: the server chooses among B and C which one will collect the board. Say B wins, so the board is stored on B client machine.
3. A comes back to the board within a new frame and becomes a normal user receiving board data from B machine.

Is this right?

Finally, notice that connecting to http://tableaunoir.irisa.fr/ seems to work, but I still receive the message "Impossible to connect to the server" when I try to create a protected board (tried from Chromium and Firefox, both under Linux Mint 20.04 at 22:08).

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

> I need some precision about the way board data are stored.
>     1. A creates a protected board and writes "Hello!"
>     2. A quit the frame (nobody owns the board from now on)
>     3. A comes back to the board within a new frame
> 
> Is it true that A doesn't see "Hello!" at point 3, but rather a fresh board?
Yes, for the moment it works like this.

> 
>     1. A creates a protected board and writes "Hello!" and sends the link to B and C
>     2. B and C connect to the board which is stored on A client machine.
>     3. A quit the frame: the server chooses among B and C which one will collect the board. Say B wins, so the board is stored on B client machine.
>     4. A comes back to the board within a new frame and becomes a normal user receiving board data from B machine (as it is for C).
> 
> Is this right?

Yes, but the protocol for choosing B is "stupid". It is the user with the smallest ID that becomes the "leader". This could be improved at some point.

> 
> Finally, notice that connecting to http://tableaunoir.irisa.fr/ seems to work, but I still receive the message "Impossible to connect to the server" when I try to create a protected board (tried from Chromium and Firefox, both under Linux Mint 20.04 at 22:08).
I am so sorry. I experienced the same problem. :( I try to improve the code on the server side. The issue is that it is not Typescript and that I cannot configure. It is so sad that web technologies are not strong typed by default. I remembered having spent one full afternoon for configuring Typescript compiler and I was unsuccessful.

**Comment by philardine** [comment]
OK, thank you, now I understand the architecture of this application a little better :-)
And good news: since your improvement, protected boards are back!

> 1. Do we have situations where there are several root users? If no, the inconsistency b) is not dramatic, and it is not urgent to repair it.
> 2. Do we have situations where we give writing permission to a non-root user? (I guess so? We could ask a question to a specific student and she could write down the answer and only she?) The interface will be too complicated maybe?
> 3. Or should we just fix to your current idea: just toggle between "all users can write" and "only root users can write"?
Let me answer to your proposals :
1. In theory there can be many root users, in my practice this has never been the case... Still I dislike inconsistencies ;-)... OK, if you opt for one root user I agree that it is not urgent.
2. I agree with you: I cannot figure out how to manage this feature with a simple interface. Moreover I am not convinced that it would be very useful to allow only one student to write rather than all.
3. I vote for this solution.

For me write rights (aka checkbox state) is a board property, root users don't own this property but only the privilege to modify it.
So these rights should logically be stored in a unique place (server side, near the password).
And when a root user modify his own checkbox, a notification should be sent to the server which broadcasts to every client in order for them to refresh their checkbox (... only if they are root users of course).

But if that's your choice, leaving this data on the client side isn't a problem.
Either way, the following scenario should be correct:
1. A makes a protected board (= is a root user) configured with no write rights.
2. B connects to this protected board as another root user, and C as a normal (unprivileged) user.
3. Now A and B can write but C cannot.
4. A checks his checkbox, magically the checkbox of B becomes also checked.
5. Now everybody can write (A, B and C).
6. B unchecks his checkbox, magically the checkbox of A becomes unchecked too.
7. Now we are back to the point 3 (A and B can write and C cannot).

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
thank you for your constructive answer. You said "I dislike inconsistencies", and "I vote for this solution". I think that is the most reasonable solution. However, in case one would to allow write permissions of non-root users too, I will leave this possibibility in the code.

With the incoming implementation (I do not know when I will do that), your scenario 1-7 will become true.
Have a nice week-end.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
thank you for your constructive answer. You say "I dislike inconsistencies" and "I vote for this solution". So probably, we will stick to that option for which the scenario 1-7 is correct.

However, I am also thinking about a collaborative mode in which one user A may decide to be the only one to draw, the other participants B and C are listening and intentionally do not want to be able to write and to disturb the presentation. B would like to present something while the others are listening, thus she clicks on sth (this checkbox which is ugly in this context), and B can write while A and C cannot. She kind of becomes the presenter. Do you think it is relevant?

If it is, there may be three options available:
- I take the lead, can write and others (including root users) cannot
- only root users can write
- all users can write

What do you think?

**Comment by philardine** [comment]
Dear François,

Thank you for this great idea, which is very interesting.
I think the interface could offer multiple modes and it would be up to a root user to decide which mode to apply:
1. Writing stick (kind of talking stick, or « bâton de parole » in french): One variable root user among other root users
2. All root users
3. All users

These three options could be set in the configuration panel.

We have already spoken about the last two options. Let's dive into option 1...
If this configuration where writing stick is set, the toolbar (or other convenient location) of every root user could show some well suited component.
This component could be something like a colored points pair, meaning (« my own write state », « rest of the world write state ») with a color code defined as :
* green: is allowed to write
* yellow: wants to be allowed to write
* red: is not allowed to write

The only possible states would be:
1. (green, red) I am allowed to write, the rest of the world is not allowed to write
2. (green, yellow) I am allowed to write, some root user in the world wants to write in place of me
3. (yellow, green) I am still not allowed to write but I want to, some root user in the world is allowed to write
4. (red, green) I am not allowed to write, some root user in the world is allowed to write
5. (red, red) nobody in the world is allowed to write

Notice that, in point 4 and 5, since I don't want to write (my first point is red), I don't care if there is a debate between other root users (to gain writing stick) or not: my second point is green if one of them is allowed to write (thus masking an eventual yellow) or red if none are.
Moreover, apart from the 5 previous configurations, no other one is possible. For example (red, yellow) never occurs: if nobody is currently allowed, the will to write is immediately satisfied (= no intermediate yellow stage).

Finally, we could imagine that the first colored point in the pair (my own write state) is reactive, so that clicking on it would switch cyclicly in this way: green -> red -> {yellow | green} and the transition yellow -> green would be automatic when the one who is currently allowed decides to give up his place to the one who asked for.

Does it sound like what you imagined?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

I really like your modes 2 and 3, and thank you for having pinpointed the inconsistency. However I find mode 1 too complicated, although I like the idea that users can ask for the permission. But, I think they can simply ask vocally no?

Your message make simply think that root users should be able to modify the write permissions of any users and that a simple interface is:
 
![image](https://user-images.githubusercontent.com/43071857/107885660-e7d0ce80-6efb-11eb-837a-29af0db84ecd.png)

Each user has a crown iff she is root. A root user can click on the "forbidden icon" or "pencil icon" in the list of users to change the writing permission of some user.

Also, I suggest to keep your modes 2 and 3. But I think the checkbox "all users can write" is not adequate. Instead, I suggest two buttons:
* a button "make that all existing and incoming users can write"
* a button "make that only privileged users can write"

What do you think? 

PS: Sorry for that, because I already started to modify tableaunoir (but without updating tableaunoir.irisa.fr).

**Comment by philardine** [comment]
Dear François,

Thank you for your answer, and please don't apologize for doing this good work!

You are quite right: voice can be used (through an auxiliary channel, however) to ask for write rights.

Let me assert some propositions, and please correct me when they are wrong:
1. All privileged users are always allowed to write (there is no more only one writer).
2. So for the sake of consistency, one root user cannot click the icon of another root user.
3. If you use buttons, how can we know in which state the board is: everybody can write / only root users?

And one last thought to let you know, but it doesn't appeal an answer.
I think your implementation will be manageable only for small groups of participants.
I sometimes use tableaunoir with many students (more or less 80). OK this is not my main use of tableaunoir, but it may happen.
I experienced that many of them give no name (they are known as "me" or even ""). Moreover it happens that their name disappears (I think this bug occurs probably after a while when there are a lot of participants... not sure).
I cannot figure out how I could set someone's rights in this context, so the only practical way to use tableaunoir in this situation is by only allowing privileged users to write.

Once more, thank you for the good work :-)

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

let us comment your propositions.
1.  Yes
2. Oh ok, yes you are right. It would be annoying for some other root users to forbid you to write! It is not so in the current (undeployed) version but I think you are right.
3. You know the state of the board by looking at the icons near by each user.

Point 3 is only manageable for small groups yes. However, we could have a summary of the state, especially when there are too many participants.
Concerning the name of users, probably the best would be to ask the name at the beginning of the session. I am not sure.

Thank you and have a nice day!!!

PS: The update of the graphical user interface is not very clean yet. Here, we would have the benefit of using reactive programming (frameworks as Vue.js, Svelte etc).

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

I pushed the new version on tableaunoir.irisa.fr.
Your points 1, 2 and 3 are implemented. For point 3, there are no summary for big groups. I guess that the two buttons are sufficient.
Also, the GUI is more optimized.

Now, as it is new, there may be some new bugs. Hope it is usable.

Have a nice evening.

**Comment by philardine** [comment]
Dear François,

Thank you.
I have just opened a new session between me and me, it **seems** to work fine.
I will try it in the real life today, Tuesday and Friday. More to come...

**Comment by philardine** [comment]
Dear François,

Yesterday everything worked fine. Today, it was a nightmare.

We were about 25, and everybody was allowed to write.
After half an hour, some lines magically disappear just after being drawn (and #113 issue came back).
After an hour, someone told me she couldn't see the board (the board was empty for her) and whoever pressed F5 got an empty board.
Someone saved the board, thus I tried to reload it. It didn't work for my participants: they saw nothing on the board. We were forced to create a new shared board and reload the saved data to be able to work... bad day!

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

thank you for reporting that. I am really sorry for what happened. I guess that what happened is:
- the bug #113 happened on your computer
- thus the action list was highly corrupted on your computer
- some bug, maybe #113, occurred on her computer
- she pressed F5 to reload and reconnect
- you were elected as the user who sends the data
- she received the corrupted data so her board was empty
- any persons pressing F5 got the same empty board for the same reason
- I can explain why the loading phase did not work but I suspect that all the local states were corrupted (because normally, loading a file is a shared action)

I should focus on:
1) fixing #113
2) improving the reliability of Tableaunoir

**Comment by francoisschwarzentruber** [comment]
Point 2 is I think related to #141.

**Comment by francoisschwarzentruber** [comment]
Dear all,
I hope you are fine. Do you think that drawing permissions are clear enough? Can I close that issue?
Thank you and have a nice day!
PS: For the connectivity issues, see #141.

**Comment by philardine** [comment]
Dear François,

IMHO the current management of write rights is quite easy and user friendly.

Thanks a lot!

**Comment by francoisschwarzentruber** [comment]
Thank you for your message. I then close that issue. :)
